dataroot: /kaggle/input/sketch2image-dataset/cufs
dataset_mode: aligned
direction: AtoB
load_size: 256
crop_size: 256
preprocess: resize_and_crop
no_flip: false
num_threads: 4

model: pix2pix
netG: unet_256
netD: pixel
norm: batch
no_dropout: false
init_type: normal
init_gain: 0.02
gan_mode: vanilla

lambda_L1: 30

batch_size: 16
n_epochs: 100
n_epochs_decay: 100
lr: 0.0002
lr_policy: step
lr_decay_iters: 50
beta1: 0.5

seed: 42

save_latest_freq: 5000
save_epoch_freq: 5
save_by_iter: false

use_wandb: true
wandb_project: sketch
wandb_entity: Sketch2Image
display_freq: 400
print_freq: 100

eval_test_freq: 200
eval_phase: test
num_test: 100
eval_batch_size: 1
eval_num_threads: 0
eval_flip: false
eval_num_fid_images: 100
eval_kid_subset_size: 10
eval_kid_subsets: 5
no_eval_test_images: false

name: cufs_ablation_c_unet256_pixel_vanilla
checkpoints_dir: ./checkpoints
